### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by frankwiles** [tolgahanuzun/test_plus#1]
Hi! 

Just a heads up there might be some confusion with an already established package [django-test-plus](https://github.com/revsys/django-test-plus. )

**Comment by tolgahanuzun** [comment]
Hello,
I don't see a problem right now. It is not a package to use within the code. More like a widget. But if there's a problem, i take care of it. :)

**Comment by frankwiles** [comment]
You just wouldn't be able to install both your test_plus and django-test-plus in the same project is all.

**Comment by tolgahanuzun** [comment]
`-e git+git@github.com:tolgahanuzun/test_plus.git@master#egg=custom_name`
Is this solution not appropriate?
